# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_name',
            field=models.CharField(default='sample', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
