# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180204_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target',
        ),
    ]
